### ISSUE TITLE
add `data-*` attributes to `section.progressive-audio` to render player state

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Player.ProgressiveAudio#15]
For every named state in `ProgressiveAudioState` there should be corresponding `data-*` attribute. These attributes can be used (optionally) by <acronym title="Cascading Style Sheets">CSS</acronym> selectors for display 🍱💄

_Exemplia_:

```scss
body>section>.player[data-credits-modal-visible="yes"] ~ .footer {
    display: none !important;
}
```
